export interface TimezoneOption {
  value: string;
  label: string;
}

export const TIMEZONES: TimezoneOption[] = [
  // ── Americas ────────────────────────────────────────────────────────────────
  { value: "Pacific/Honolulu",                  label: "(-10:00) Honolulu" },
  { value: "America/Anchorage",                 label: "(-09:00) Anchorage" },
  { value: "America/Los_Angeles",               label: "(-08:00) Los Angeles" },
  { value: "America/Vancouver",                 label: "(-08:00) Vancouver" },
  { value: "America/Tijuana",                   label: "(-08:00) Tijuana" },
  { value: "America/Denver",                    label: "(-07:00) Denver" },
  { value: "America/Edmonton",                  label: "(-07:00) Edmonton" },
  { value: "America/Phoenix",                   label: "(-07:00) Phoenix" },
  { value: "America/Chihuahua",                 label: "(-07:00) Chihuahua" },
  { value: "America/Mazatlan",                  label: "(-07:00) Mazatlan" },
  { value: "America/Chicago",                   label: "(-06:00) Chicago" },
  { value: "America/Winnipeg",                  label: "(-06:00) Winnipeg" },
  { value: "America/Mexico_City",               label: "(-06:00) Mexico City" },
  { value: "America/Monterrey",                 label: "(-06:00) Monterrey" },
  { value: "America/Guatemala",                 label: "(-06:00) Guatemala" },
  { value: "America/Tegucigalpa",               label: "(-06:00) Tegucigalpa" },
  { value: "America/El_Salvador",               label: "(-06:00) San Salvador" },
  { value: "America/Managua",                   label: "(-06:00) Managua" },
  { value: "America/Costa_Rica",                label: "(-06:00) San José" },
  { value: "America/Regina",                    label: "(-06:00) Saskatchewan" },
  { value: "America/New_York",                  label: "(-05:00) New York" },
  { value: "America/Toronto",                   label: "(-05:00) Toronto" },
  { value: "America/Detroit",                   label: "(-05:00) Detroit" },
  { value: "America/Indiana/Indianapolis",      label: "(-05:00) Indianapolis" },
  { value: "America/Bogota",                    label: "(-05:00) Bogotá" },
  { value: "America/Lima",                      label: "(-05:00) Lima" },
  { value: "America/Guayaquil",                 label: "(-05:00) Quito" },
  { value: "America/Panama",                    label: "(-05:00) Panamá" },
  { value: "America/Havana",                    label: "(-05:00) La Habana" },
  { value: "America/Kingston",                  label: "(-05:00) Kingston" },
  { value: "America/Halifax",                   label: "(-04:00) Halifax" },
  { value: "America/Caracas",                   label: "(-04:00) Caracas" },
  { value: "America/La_Paz",                    label: "(-04:00) La Paz" },
  { value: "America/Manaus",                    label: "(-04:00) Manaus" },
  { value: "America/Puerto_Rico",               label: "(-04:00) Puerto Rico" },
  { value: "America/Santo_Domingo",             label: "(-04:00) Santo Domingo" },
  { value: "America/Barbados",                  label: "(-04:00) Barbados" },
  { value: "America/Santiago",                  label: "(-04:00) Santiago" },
  { value: "America/Asuncion",                  label: "(-04:00) Asunción" },
  { value: "America/St_Johns",                  label: "(-03:30) St. John's" },
  { value: "America/Sao_Paulo",                 label: "(-03:00) São Paulo" },
  { value: "America/Argentina/Buenos_Aires",    label: "(-03:00) Buenos Aires" },
  { value: "America/Argentina/Cordoba",         label: "(-03:00) Córdoba" },
  { value: "America/Argentina/Mendoza",         label: "(-03:00) Mendoza" },
  { value: "America/Argentina/Rosario",         label: "(-03:00) Rosario" },
  { value: "America/Argentina/Tucuman",         label: "(-03:00) Tucumán" },
  { value: "America/Argentina/Salta",           label: "(-03:00) Salta" },
  { value: "America/Argentina/Jujuy",           label: "(-03:00) Jujuy" },
  { value: "America/Argentina/San_Luis",        label: "(-03:00) San Luis" },
  { value: "America/Argentina/Ushuaia",         label: "(-03:00) Ushuaia" },
  { value: "America/Montevideo",                label: "(-03:00) Montevideo" },
  { value: "America/Recife",                    label: "(-03:00) Recife" },
  { value: "America/Fortaleza",                 label: "(-03:00) Fortaleza" },
  { value: "America/Bahia",                     label: "(-03:00) Salvador" },
  { value: "America/Belem",                     label: "(-03:00) Belém" },
  { value: "America/Maceio",                    label: "(-03:00) Maceió" },
  { value: "America/Paramaribo",                label: "(-03:00) Paramaribo" },
  { value: "America/Cayenne",                   label: "(-03:00) Cayena" },
  { value: "America/Godthab",                   label: "(-03:00) Nuuk (Greenland)" },

  // ── Western Europe ───────────────────────────────────────────────────────────
  { value: "UTC",                               label: "(+00:00) UTC" },
  { value: "Europe/London",                     label: "(+00:00) London" },
  { value: "Europe/Dublin",                     label: "(+00:00) Dublin" },
  { value: "Europe/Lisbon",                     label: "(+00:00) Lisbon" },
  { value: "Europe/Amsterdam",                  label: "(+01:00) Amsterdam" },
  { value: "Europe/Berlin",                     label: "(+01:00) Berlin" },
  { value: "Europe/Brussels",                   label: "(+01:00) Brussels" },
  { value: "Europe/Copenhagen",                 label: "(+01:00) Copenhagen" },
  { value: "Europe/Madrid",                     label: "(+01:00) Madrid" },
  { value: "Europe/Paris",                      label: "(+01:00) Paris" },
  { value: "Europe/Rome",                       label: "(+01:00) Rome" },
  { value: "Europe/Stockholm",                  label: "(+01:00) Stockholm" },
  { value: "Europe/Zurich",                     label: "(+01:00) Zurich" },
  { value: "Europe/Vienna",                     label: "(+01:00) Vienna" },
  { value: "Europe/Warsaw",                     label: "(+01:00) Warsaw" },
  { value: "Europe/Athens",                     label: "(+02:00) Athens" },
  { value: "Europe/Bucharest",                  label: "(+02:00) Bucharest" },
  { value: "Europe/Helsinki",                   label: "(+02:00) Helsinki" },
  { value: "Europe/Kiev",                       label: "(+02:00) Kyiv" },
];
